# Generated by Django 4.2.13 on 2024-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator_img',
            field=models.FileField(blank=True, null=True, upload_to='creators/', verbose_name='Creator img'),
        ),
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='reviews/', verbose_name='Reviews img'),
        ),
    ]
