# Generated by Django 4.2.1 on 2024-06-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_creator_img_review_reviews_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creator_img',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviews_img',
        ),
    ]
