# Generated by Django 4.2.1 on 2024-06-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_creator_img_review_reviews_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator_img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='creator_img/', verbose_name='Creator img'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviews_img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='reviews_img/', verbose_name='Reviews img'),
        ),
    ]
