# Generated by Django 4.2.1 on 2024-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='img',
            field=models.FileField(default=None, upload_to='deliveru_methods', verbose_name='img'),
        ),
    ]
