# Generated by Django 4.2.1 on 2024-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Payment URL'),
        ),
    ]
